### ISSUE TITLE
APIを使わないデータの受け渡しのテスト

### ISSUE THREAD

**Issue by Fuga-Kawamata** [KazuMatsuHack9981/vue-rails-app#11]
[ref_qiita]: https://qiita.com/t0yohei/items/d516fefaaad69b4022ec#html-%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E5%B1%9E%E6%80%A7%E3%81%AB%E5%80%A4%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%97%E3%81%A6%E6%B8%A1%E3%81%99%E6%96%B9%E6%B3%95

## 概要
.html.erbに直接データを置くことでデータを受け渡してみる。（[参考Qiita][ref_qiita]）

## 手順
（Rails周りはわからんのでざっくり）
1. @KazuMatsuHack9981 Rails側でデータを用意する。
1. @KazuMatsuHack9981 .html.erb内で、 `content_tag` なるものを使って `div` 要素の `data` 属性にデータをセットする（[参考][ref_qiita]参照）。
    註: Vue側では↑でデータセットした要素を（ `getElementById` 等で）取得する必要があるので、要素を識別できる属性（まあ `id` が無難）を付けてください。
1. @Fuga-Kawamata 要素を取得してrender関数経由でpropsとしてデータ取得・表示する。

## その他
Controller,Viewを新しく作るか既存のものに付け足すかはRails側の管理しやすいほうで。Viewを新規に作る場合はVueも新規。再利用（practice/indexを使う）の場合はVueも再利用。

**Comment by Fuga-Kawamata** [comment]
id付けてって書いたけど、俺があとで勝手につければいいか。どっちでもいいや。

**Comment by KazuMatsuHack9981** [comment]
> Controller,Viewを新しく作るか既存のものに付け足すかはRails側の管理しやすいほうで。  

同じコントローラにindex2みたいな感じでつくります！

> id付けてって書いたけど、俺があとで勝手につければいいか。どっちでもいいや。  

つけれたらつけてみる！
