### ISSUE TITLE
画像の表示・アップロード

### ISSUE THREAD

**Issue by Fuga-Kawamata** [KazuMatsuHack9981/vue-rails-app#19]
## 表示
~~https://blog.fakiyer.com/entry/2018/12/04/152353~~

~~https://tech.enechange.co.jp/entry/2019/01/31/160037~~

https://gorails.com/forum/how-do-i-use-images-inside-my-vue-single-file-components

~~https://stackoverflow.com/questions/45550779/how-to-access-assets-with-webpacker-gem~~

### Vue->rails
[RailsとVue.jsを使ってプレビュー付きの画像登録機能を作ってみる](https://qiita.com/me-654393/items/9570cc2a305b7b1c2e8b)  
↑formの大枠をRubyで書いてる（.html.erbにいろいろ書いてる）

[Vue on RailsでActive Storageを使って画像を保存する](https://qiita.com/tabakazu/items/5489632c534c56db6a4d)  
↑フロント全部Vueで書いてる（.html.erbはjavascript_pack_tagだけ）

### Rails->Vue
[【Rails】Railsに保存した画像ファイルをVue.js側で表示するサンプルコード（Base64、Active Storage使用）](https://qiita.com/terufumi1122/items/bdc96617c818dac01b6d)

### 参考
[【Rails 5.2】 Active Storageの使い方](https://qiita.com/hmmrjn/items/7cc5e5348755c517458a)

**Comment by KazuMatsuHack9981** [comment]
[これ](https://gorails.com/forum/how-do-i-use-images-inside-my-vue-single-file-components)の option 4 がいいと思う。option 1の webpackerの resolves path使ってるの多いけど、コンパイル遅くなるのはやだから。
