### ISSUE TITLE
ファイル名・フォルダ名がダブっているときの対処

### ISSUE THREAD

**Issue by Fuga-Kawamata** [KazuMatsuHack9981/vue-rails-app#85]
#### ファイル名が重複してると
filedatasのキーがファイル名なので、ファイルの内容が、重複してるファイル達のうち１ファイルぶんしか残らない
#### フォルダ名が重複してると
collapseのidがフォルダ名なので、explorer内でのフォルダの開閉時に、同一名のフォルダが一緒に開閉する

## 対処
filetreeに、zipファイルのルートからのpath（あるいは、各ファイル・フォルダで一意になるようなidなら何でも）を付加することで、
#### ファイル名の重複問題は
キーをそのpathにすれば解決
#### フォルダ名の重複問題は
collapseのidをそのpathにすれば解決

## 作業
1. (バック)filetreeに、zipファイルのルートからのpathを付加
1. (バック)filedatasのキーをそのpathにする
1. (フロント)collapseのidをそのpathにする
1. (フロント)ファイル・フォルダクリック時の引数をそのpathにする

**Comment by KazuMatsuHack9981** [comment]
![image](https://user-images.githubusercontent.com/56915604/81962948-6d62dd80-964f-11ea-9fcf-e44f17c0f7cc.png)
> filetreeに、zipファイルのルートからのpathを付加
これって画像のファイル名のbbb.txtのところをパスにすれば良い感じ？

**Comment by Fuga-Kawamata** [comment]
いや、nameも結局使うのでフロントでpathから切り出すのは二度手間だから（あとフォルダのpathも欲しいから）、こんな感じにpathを加えてほしい
![image](https://user-images.githubusercontent.com/58324226/82004591-41bb1400-969e-11ea-9926-0f150e5170e1.png)

**Comment by KazuMatsuHack9981** [comment]
コード思いつくのが早い！ｗ
了解！それ翻訳して付け足しておくわ
