### ISSUE TITLE
コマンドのページにuserを表示

### ISSUE THREAD

**Issue by Fuga-Kawamata** [KazuMatsuHack9981/vue-rails-app#89]
## 概要
コマンド一覧の各コマンドや、コマンド詳細のページに、そのコマンドのuser(author)を表示。クリックするとそのuserのプロフィールに飛びたい。

#### 候補１
/user_pages/index を /user_pages/index/[:id]にする
#### 候補２
リンクをクリックしたらidをcookieに控え、遷移後にそれを参照する
#### 候補３
/user_pages/index?id=[id]
#### ~候補４~
~erb内で `<%= current_user.id %>`~ ←違った、ここでは使えないや

**Comment by KazuMatsuHack9981** [comment]
あ、なんといつはUserモデルとCommandモデルは関連づいているので、command.userでできちゃうんです！

**Comment by Fuga-Kawamata** [comment]
なるほど了解、上の候補１って簡単にできる？

**Comment by KazuMatsuHack9981** [comment]
ああできるはできるんだけど、なるべくindexにidパラメータは付加したくないんだよね...
user_pages/indexを保ったまま今あるapi/user_pages/index/[:id]を使うっていうのは難しい？
