### ISSUE TITLE
コマンドページにフィルタ機能追加

### ISSUE THREAD

**Issue by KazuMatsuHack9981** [KazuMatsuHack9981/vue-rails-app#91]
## 現状
全コマンド一覧ページはあるが、各ユーザーのコマンド一覧ページとかは無い

## 仕様
フィルタはvue側の機能で追加
(バックでやるとurl変わったりして画面遷移が必要になるため)

## その他の追加項目
* "もっと見る" のリンク先をそのuserのフィルタのかかったコマンド一覧ページにできたらやってみてほしいmm

**Comment by Fuga-Kawamata** [comment]
> "もっと見る" のリンク

これindexだからidつけない方向のほうがいいよね

**Comment by KazuMatsuHack9981** [comment]
そうなのよね
commandの場合は
* index：全コマンド一覧
* show：各コマンドの詳細ページ
の役割だからshowに変える事ができんのよ…

まぁ最悪indexにid付けるって感じかな

**Comment by Fuga-Kawamata** [comment]
/command_pages/index?id=1みたいなのは？

**Comment by KazuMatsuHack9981** [comment]
paramsと同じ感じで影響ある感じです...

**Comment by Fuga-Kawamata** [comment]
なるほどね...じゃあid付与を避けるとしたらcookieか

**Comment by KazuMatsuHack9981** [comment]
うおおcookie私使ったことないけど、確かにフィルタなんて個人情報でもなんでもないしcookieはアリアリだと思う！

**Comment by Fuga-Kawamata** [comment]
あ、違うわ、erbに `<%= current_user.id %>` って書いてそれをvueに持ってくるという方法を見つけたのでそれを使えばいいんだわ（開発者ツールでの書き換えもできないはず）
